default: &default
  thumbnail_width: 200
  thumbnail_height: 200
  hdtv_height: 1080
  image_cache_dir: 'public/cache/' # relative path inside Rails.root
  image_prefix: 'KSC'
  thumbnail_path_regex: !ruby/regexp /(^[0-9a-z]{32})_([0-9]+)x([0-9]+)\.([a-z0-9]+)/i
  hdtv_path_regex: !ruby/regexp /(^[0-9a-z]{32})_([0-9]+)\.([a-z0-9]+)/i
  use_aws: false # If AWS is to be used for images
  api_url: 'http://demo.pixomatix.com' # API to use to show galleries and images. Should be either blank or URL.

development:
  <<: *default
  image_root: ['/path/to/your/pics/dir/', '/vacation/pics/']
  use_aws: false
  api_url: ''

test:
  <<: *default
  image_root: []
  api_url: ''

stage:
  <<: *default
  image_root: []
  api_url: ''

production:
  <<: *default
  image_root: []
  api_url: ''
